import type { Application, SchemeRule, User, KPIData, MeritListEntry } from './types';

export const SCHEMES: SchemeRule[] = [
  {
    code: 'NFST',
    name: 'National Fellowship for ST',
    description: 'JRF/SRF for PhD research scholars from ST communities',
    maxIncome: 600000,
    minMarksPercent: 55,
    maxAge: 40,
    stipendMonthly: 31000,
    requiredDocs: ['CASTE_CERTIFICATE', 'INCOME_CERTIFICATE', 'MARKSHEET', 'RESEARCH_SYNOPSIS', 'BANK_PASSBOOK', 'AADHAAR'],
    seats: 700,
    pvtgPriority: true,
    femaleQuotaPercent: 30,
    pwdQuotaPercent: 5,
    active: true,
  },
  {
    code: 'NOS',
    name: 'National Overseas Scholarship',
    description: 'Fellowship for ST students pursuing Masters/PhD abroad',
    maxIncome: 800000,
    minMarksPercent: 60,
    maxAge: 35,
    stipendMonthly: 150000,
    foreignUniversityQSRank: 500,
    requiredDocs: ['CASTE_CERTIFICATE', 'INCOME_CERTIFICATE', 'MARKSHEET', 'OFFER_LETTER', 'PASSPORT_PHOTO', 'AADHAAR'],
    seats: 20,
    pvtgPriority: true,
    femaleQuotaPercent: 30,
    pwdQuotaPercent: 5,
    active: true,
  },
  {
    code: 'TOP_CLASS',
    name: 'Top Class Education Scheme',
    description: 'Scholarships for ST students in premier institutions (IITs, IIMs, AIIMS etc.)',
    maxIncome: 600000,
    minMarksPercent: 60,
    maxAge: 30,
    stipendMonthly: 75000,
    requiredDocs: ['CASTE_CERTIFICATE', 'INCOME_CERTIFICATE', 'MARKSHEET', 'BANK_PASSBOOK', 'AADHAAR'],
    seats: 1200,
    pvtgPriority: true,
    femaleQuotaPercent: 30,
    pwdQuotaPercent: 5,
    active: true,
  },
  {
    code: 'POST_MATRIC',
    name: 'Post-Matric Scholarship',
    description: 'Scholarships for ST students studying post-10th grade',
    maxIncome: 250000,
    minMarksPercent: 45,
    maxAge: 35,
    stipendMonthly: 8000,
    requiredDocs: ['CASTE_CERTIFICATE', 'INCOME_CERTIFICATE', 'MARKSHEET', 'BANK_PASSBOOK', 'AADHAAR'],
    seats: 50000,
    pvtgPriority: true,
    femaleQuotaPercent: 30,
    pwdQuotaPercent: 5,
    active: true,
  },
  {
    code: 'PRE_MATRIC',
    name: 'Pre-Matric Scholarship',
    description: 'Scholarships for ST students in Classes 9-10',
    maxIncome: 250000,
    minMarksPercent: 40,
    maxAge: 18,
    stipendMonthly: 3500,
    requiredDocs: ['CASTE_CERTIFICATE', 'INCOME_CERTIFICATE', 'MARKSHEET', 'BANK_PASSBOOK', 'AADHAAR'],
    seats: 100000,
    pvtgPriority: true,
    femaleQuotaPercent: 30,
    pwdQuotaPercent: 5,
    active: true,
  },
];

export const MOCK_USERS: User[] = [
  { id: 'u1', name: 'Priya Meena', email: 'priya@student.ac.in', role: 'APPLICANT', apaarId: 'APAAR-2024-001234', state: 'Rajasthan', institution: 'University of Rajasthan' },
  { id: 'u2', name: 'Arjun Munda', email: 'arjun@student.ac.in', role: 'APPLICANT', apaarId: 'APAAR-2024-005678', state: 'Jharkhand', institution: 'BIT Mesra' },
  { id: 'u3', name: 'Dr. Kavita Soren', email: 'kavita.soren@ino.ac.in', role: 'INSTITUTE_NODAL', institution: 'BIT Mesra' },
  { id: 'u4', name: 'Rajesh Kumar IAS', email: 'rajesh.kumar@nic.in', role: 'SCRUTINY_OFFICER' },
  { id: 'u5', name: 'JS Tribal Affairs', email: 'js@mota.gov.in', role: 'MINISTRY_ADMIN' },
];

export const MOCK_APPLICATIONS: Application[] = [
  {
    id: 'APP-2024-NFST-001',
    applicantId: 'u1',
    applicantName: 'Priya Meena',
    apaarId: 'APAAR-2024-001234',
    aadhaarHash: 'sha256:a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4',
    schemeCode: 'NFST',
    schemeName: 'National Fellowship for ST',
    state: 'Rajasthan',
    institution: 'University of Rajasthan',
    annualIncome: 480000,
    pgMarksPercent: 72.5,
    age: 26,
    gender: 'FEMALE',
    isPwD: false,
    isPVTG: false,
    status: 'AI_SCRUTINY',
    submittedAt: '2024-11-01T10:30:00Z',
    updatedAt: '2024-11-03T14:20:00Z',
    compositeScore: 72.5,
    deficiencies: [],
    documents: [
      { id: 'd1', applicationId: 'APP-2024-NFST-001', type: 'CASTE_CERTIFICATE', fileName: 'caste_cert.pdf', uploadedAt: '2024-11-01T10:30:00Z', status: 'VERIFIED', aiExtraction: { applicantName: 'Priya Meena', certificateNumber: 'RJ/CC/2024/78543', issuingAuthority: 'Tehsildar, Jaipur', subCaste: 'Meena', issueDate: '2024-01-15', validUntil: '2027-01-14', confidenceScore: 94, confidenceLevel: 'HIGH', anomalies: [], extractedFields: { state: 'Rajasthan', district: 'Jaipur' } } },
      { id: 'd2', applicationId: 'APP-2024-NFST-001', type: 'INCOME_CERTIFICATE', fileName: 'income_cert.pdf', uploadedAt: '2024-11-01T10:30:00Z', status: 'VERIFIED', aiExtraction: { applicantName: 'Priya Meena', incomeAmount: 480000, issuingAuthority: 'SDO, Jaipur', issueDate: '2024-03-30', validUntil: '2025-03-31', confidenceScore: 91, confidenceLevel: 'HIGH', anomalies: [], extractedFields: { financialYear: '2023-24' } } },
      { id: 'd3', applicationId: 'APP-2024-NFST-001', type: 'MARKSHEET', fileName: 'pg_marksheet.pdf', uploadedAt: '2024-11-01T10:30:00Z', status: 'VERIFIED', aiExtraction: { applicantName: 'Priya Meena', certificateNumber: 'UOR/PG/2023/12345', issuingAuthority: 'University of Rajasthan', issueDate: '2023-06-30', confidenceScore: 88, confidenceLevel: 'MEDIUM', anomalies: [], extractedFields: { percentage: '72.5', degree: 'M.Sc. Biochemistry' } } },
    ],
    quarterlyReports: [],
  },
  {
    id: 'APP-2024-NOS-002',
    applicantId: 'u2',
    applicantName: 'Arjun Munda',
    apaarId: 'APAAR-2024-005678',
    aadhaarHash: 'sha256:b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5',
    schemeCode: 'NOS',
    schemeName: 'National Overseas Scholarship',
    state: 'Jharkhand',
    institution: 'BIT Mesra',
    annualIncome: 650000,
    pgMarksPercent: 78.2,
    age: 28,
    gender: 'MALE',
    isPwD: false,
    isPVTG: true,
    status: 'DEFICIENCY_RAISED',
    submittedAt: '2024-11-02T09:15:00Z',
    updatedAt: '2024-11-04T11:00:00Z',
    compositeScore: 76.1,
    deficiencies: [
      { id: 'def1', applicationId: 'APP-2024-NOS-002', documentType: 'INCOME_CERTIFICATE', reason: 'Income certificate expired on 31-03-2024. Please upload fresh certificate for FY 2024-25 issued by competent authority.', raisedAt: '2024-11-04T11:00:00Z', status: 'OPEN' },
    ],
    documents: [
      { id: 'd4', applicationId: 'APP-2024-NOS-002', type: 'CASTE_CERTIFICATE', fileName: 'caste_munda.pdf', uploadedAt: '2024-11-02T09:15:00Z', status: 'VERIFIED', aiExtraction: { applicantName: 'Arjun Munda', certificateNumber: 'JH/CC/2024/34521', issuingAuthority: 'Circle Officer, Ranchi', subCaste: 'Munda', issueDate: '2024-02-10', validUntil: '2027-02-09', confidenceScore: 96, confidenceLevel: 'HIGH', anomalies: [], extractedFields: { state: 'Jharkhand', district: 'Ranchi' } } },
      { id: 'd5', applicationId: 'APP-2024-NOS-002', type: 'INCOME_CERTIFICATE', fileName: 'income_old.pdf', uploadedAt: '2024-11-02T09:15:00Z', status: 'DEFICIENT', aiExtraction: { applicantName: 'Arjun Munda', incomeAmount: 650000, issuingAuthority: 'SDO, Ranchi', issueDate: '2023-03-30', validUntil: '2024-03-31', confidenceScore: 65, confidenceLevel: 'LOW', anomalies: ['Certificate expired on 31-03-2024', 'Issue date older than 1 year'], extractedFields: { financialYear: '2022-23' } } },
      { id: 'd6', applicationId: 'APP-2024-NOS-002', type: 'OFFER_LETTER', fileName: 'oxford_offer.pdf', uploadedAt: '2024-11-02T09:15:00Z', status: 'VERIFIED', aiExtraction: { applicantName: 'Arjun Munda', issuingAuthority: 'University of Oxford', issueDate: '2024-09-01', confidenceScore: 92, confidenceLevel: 'HIGH', anomalies: [], extractedFields: { university: 'University of Oxford', qsRank: '3', program: 'DPhil Computer Science' } } },
    ],
    quarterlyReports: [],
  },
  {
    id: 'APP-2024-NFST-003',
    applicantId: 'u6',
    applicantName: 'Sita Bhil',
    apaarId: 'APAAR-2024-009012',
    aadhaarHash: 'sha256:c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6',
    schemeCode: 'NFST',
    schemeName: 'National Fellowship for ST',
    state: 'Madhya Pradesh',
    institution: 'IISER Bhopal',
    annualIncome: 320000,
    pgMarksPercent: 81.0,
    age: 24,
    gender: 'FEMALE',
    isPwD: true,
    isPVTG: false,
    status: 'SUBMITTED',
    submittedAt: '2024-11-05T08:00:00Z',
    updatedAt: '2024-11-05T08:00:00Z',
    compositeScore: 81.0,
    deficiencies: [],
    documents: [
      { id: 'd7', applicationId: 'APP-2024-NFST-003', type: 'CASTE_CERTIFICATE', fileName: 'caste_bhil.pdf', uploadedAt: '2024-11-05T08:00:00Z', status: 'PENDING' },
      { id: 'd8', applicationId: 'APP-2024-NFST-003', type: 'INCOME_CERTIFICATE', fileName: 'income_bhil.pdf', uploadedAt: '2024-11-05T08:00:00Z', status: 'PENDING' },
    ],
    quarterlyReports: [],
  },
  {
    id: 'APP-2024-NOS-004',
    applicantId: 'u7',
    applicantName: 'Ramu Gond',
    apaarId: 'APAAR-2024-003456',
    aadhaarHash: 'sha256:d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1',
    schemeCode: 'NOS',
    schemeName: 'National Overseas Scholarship',
    state: 'Chhattisgarh',
    institution: 'NIT Raipur',
    annualIncome: 780000,
    pgMarksPercent: 68.5,
    age: 32,
    gender: 'MALE',
    isPwD: false,
    isPVTG: false,
    status: 'APPROVED',
    submittedAt: '2024-10-15T12:00:00Z',
    updatedAt: '2024-11-01T09:00:00Z',
    compositeScore: 70.8,
    deficiencies: [],
    documents: [
      { id: 'd9', applicationId: 'APP-2024-NOS-004', type: 'CASTE_CERTIFICATE', fileName: 'caste_gond.pdf', uploadedAt: '2024-10-15T12:00:00Z', status: 'VERIFIED' },
      { id: 'd10', applicationId: 'APP-2024-NOS-004', type: 'INCOME_CERTIFICATE', fileName: 'income_gond.pdf', uploadedAt: '2024-10-15T12:00:00Z', status: 'VERIFIED' },
    ],
    quarterlyReports: [
      { id: 'qr1', applicationId: 'APP-2024-NOS-004', quarter: 1, year: 2024, summary: 'Completed initial literature review and submitted first chapter draft.', uploadedAt: '2024-04-15T10:00:00Z', supervisorApproved: true, supervisorApprovedAt: '2024-04-20T14:00:00Z', stipendReleased: true, stipendReleasedAt: '2024-04-25T09:00:00Z' },
    ],
  },
];

export const KPI_DATA: KPIData = {
  totalApplicants: 12847,
  approvedCount: 8234,
  pendingCount: 3891,
  deficiencyCount: 722,
  totalFundsSanctioned: 2847600000,
  femaleRatio: 0.34,
  stateWiseDistribution: [
    { state: 'Madhya Pradesh', count: 2340 },
    { state: 'Rajasthan', count: 1876 },
    { state: 'Jharkhand', count: 1654 },
    { state: 'Odisha', count: 1432 },
    { state: 'Chhattisgarh', count: 1287 },
    { state: 'Gujarat', count: 987 },
    { state: 'Maharashtra', count: 876 },
    { state: 'Andhra Pradesh', count: 654 },
    { state: 'West Bengal', count: 543 },
    { state: 'Others', count: 1198 },
  ],
  schemeWiseDistribution: [
    { scheme: 'Post-Matric', count: 8234 },
    { scheme: 'NFST', count: 2341 },
    { scheme: 'Top Class', count: 1234 },
    { scheme: 'NOS', count: 876 },
    { scheme: 'Pre-Matric', count: 162 },
  ],
  monthlyTrend: [
    { month: 'Jul', applications: 1200, approvals: 890 },
    { month: 'Aug', applications: 2340, approvals: 1780 },
    { month: 'Sep', applications: 3120, approvals: 2340 },
    { month: 'Oct', applications: 4560, approvals: 3450 },
    { month: 'Nov', applications: 1627, approvals: 874 },
  ],
};

export const MERIT_LIST: MeritListEntry[] = [
  { rank: 1, applicationId: 'APP-2024-NFST-003', applicantName: 'Sita Bhil', apaarId: 'APAAR-2024-009012', state: 'Madhya Pradesh', institution: 'IISER Bhopal', pgMarksPercent: 81.0, compositeScore: 81.0, gender: 'FEMALE', isPwD: true, isPVTG: false, category: 'PWD_QUOTA', status: 'SELECTED' },
  { rank: 2, applicationId: 'APP-2024-NFST-001', applicantName: 'Priya Meena', apaarId: 'APAAR-2024-001234', state: 'Rajasthan', institution: 'University of Rajasthan', pgMarksPercent: 72.5, compositeScore: 72.5, gender: 'FEMALE', isPwD: false, isPVTG: false, category: 'FEMALE_QUOTA', status: 'SELECTED' },
  { rank: 3, applicationId: 'APP-2024-NOS-002', applicantName: 'Arjun Munda', apaarId: 'APAAR-2024-005678', state: 'Jharkhand', institution: 'BIT Mesra', pgMarksPercent: 78.2, compositeScore: 76.1, gender: 'MALE', isPwD: false, isPVTG: true, category: 'PVTG_PRIORITY', status: 'SELECTED' },
  { rank: 4, applicationId: 'APP-2024-NOS-004', applicantName: 'Ramu Gond', apaarId: 'APAAR-2024-003456', state: 'Chhattisgarh', institution: 'NIT Raipur', pgMarksPercent: 68.5, compositeScore: 70.8, gender: 'MALE', isPwD: false, isPVTG: false, category: 'GENERAL_ST', status: 'SELECTED' },
];

export const DEFICIENCY_REMARK_TEMPLATES = [
  'Income certificate expired. Please upload fresh certificate for current financial year (FY 2024-25) issued by competent authority (SDO/Tehsildar).',
  'Caste certificate not legible / stamp unclear. Please re-upload a clear, high-resolution scan.',
  'Sub-caste stated in certificate does not match Constitution (Scheduled Tribes) Order for the declared state.',
  'Marksheet not attested by institution. Please get it attested by the Registrar/Principal with seal.',
  'Bank account details mismatch. Account number on passbook does not match submitted details.',
  'Research synopsis exceeds word limit of 1000 words. Please revise and resubmit.',
  'Offer letter from foreign university does not mention QS World Ranking. Attach university ranking proof separately.',
  'Annual income exceeds scheme eligibility ceiling. Clarification required from issuing authority.',
];
